export const APP_CONSTANTS = {
  DEFAULT_SAFETY_FLOOR: 0,
  DEFAULT_LOCKED_SAVINGS: 0,
  SIMULATED_LEFTOVER_BUDGET: 360,
  PROJECTED_ANNUAL_USD: 432000,
  AUTO_SWEEP_INTERVAL_MS: 60000,
  UNDO_WINDOW_MS: 5000,
} as const;

export type AppConstants = typeof APP_CONSTANTS;
